# Generated by Django 3.2.5 on 2021-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farbe',
            field=models.CharField(default='Blau', max_length=100),
        ),
    ]
