# Generated by Django 3.2.5 on 2021-08-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_slug'),
        ('store', '0003_product_farbe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_categories', to='category.category'),
        ),
    ]
