# Generated by Django 3.2.5 on 2021-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_article_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['titr']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='headline',
            new_name='titr',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title',
            new_name='name',
        ),
    ]
