# Generated by Django 3.2.5 on 2021-08-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210822_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
    ]
