# Generated by Django 3.2.5 on 2021-08-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bilingadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilingadress',
            name='hause_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
