# Generated by Django 3.2.5 on 2021-09-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bilingadress_hause_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilingadress',
            name='hause_number',
            field=models.IntegerField(),
        ),
    ]
