# Generated by Django 3.2.5 on 2021-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
    ]
