# Generated by Django 3.2.5 on 2021-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=1.2),
        ),
    ]
