# Generated by Django 3.2.5 on 2021-09-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
    ]
